version: "2"

services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    command: server /data
