version: "2.3"

services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: ${SYSTEM_TIMELINEID}
    command: server /data
    networks:
      - internal
  url-bucket:
    image: ${DOCKERIMAGENAME}
    hostname: ${DOCKERHOSTNAME}
    labels:
      caddy.address: ${DOCKERHOSTNAME}
      caddy.header /: Strict-Transport-Security "max-age=31536000;"'
      caddy.proxy.websocket: transparent
      caddy.push /: |
         /swagger/v1/swagger.json
         /swagger/swagger-ui-bundle.js
         /swagger/swagger-ui.css
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: ${SYSTEM_TIMELINEID}
      MINIO_ENDPOINT: minio:9000
      MINIO_SSL: "false" 
    networks:
      - internal
      - caddy_caddy

networks:
  internal:
  caddy_caddy:
    external: true