version: "2"

services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2018-04-04T05-20-54Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
  url-bucket:
    image: 0xff/url-bucket
    ports:
      - "8080:80"
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ENDPOINT: minio:9000
      MINIO_SSL: "false"