version: "2"

services:
  
  url-bucket:
    image: quay.io/0xff/url-bucket # also avaiable on dockerhub, but quay is faster (for me)
    # build: ../ # use this instead of the `image` above to build from source
    ports:
      - "8080:8080"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ENDPOINT: minio:9000
      MINIO_SSL: "false" # consider setting up tls: https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html

  minio:
    hostname: minio
    image: minio/minio:RELEASE.2018-09-25T21-34-43Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:      
